# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Shellhack' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Shellhack

	pod 'Firebase/Auth'
	pod 'GoogleSignIn'
	pod 'Firebase/Firestore'
	pod 'Firebase/Database'
	pod 'FirebaseFirestoreSwift', '> 7.0-beta'
	pod 'PorterStemmer2'



  target 'ShellhackTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ShellhackUITests' do
    # Pods for testing
  end

end
